### ISSUE TITLE
Socket colours in the gem "tab"

### ISSUE THREAD

**Issue by PROdotes** [Dav1dde/pasteofexile#11]
Maybe just add a circle in front of behind the gem name so it's easy to know what sockets you need at a glance?
Example:
Rolling Magma (B)
|-Combustion (B)
|-Arcane Surge (B)
|- Lifetap (R)

it can stay RGB but also be coloured I guess :)

**Comment by Dav1dde** [comment]
Idea for post league so I don't forget: Color the first character

**Comment by PROdotes** [comment]
could also use ● in front... not sure what ascii code it is :)

**Comment by cdrg** [comment]
Some sort of color coding of gem names is kind of critical for me, since I use PoBs to quickly create filters. I need to be able to tell the color of gems at a glance. Ideally color the entire name the way PoB does.

**Comment by norecha** [comment]
This would be a great addition!

**Comment by Dav1dde** [comment]
For everyone following, it's implemented now. Coloring the entire line looks decent imo:

![image](https://github.com/Dav1dde/pasteofexile/assets/255721/23d16f22-a740-4fd6-8685-8b452c53866d)

If you have any ideas how to make it look better (different colors, maybe only coloring certain elements) let me know!
