### ISSUE TITLE
PoBB Trees don't load on iPhones 

### ISSUE THREAD

**Issue by Taillow500** [Dav1dde/pasteofexile#13]
Hi! I'm a console player so I don't view PoBB's from PC, I view them from iPhone however it appears that its broken pretty much across multiple iPhone models. 

I've confirmed that its not just Safari either. I've tried FireFox, Chrome, Safari and none will display the tree's on any PoBB's. 
![IMG_2426](https://user-images.githubusercontent.com/12942530/235328893-0c2cf809-ed47-49da-8dde-b778c8ba7d40.png)

**Comment by Dav1dde** [comment]
Unfortunately I think this is related to #9 - iOS uses the same renderer for all browsers (Chrome, Firefox, Safari) so it is expected that no browser works if Safari can't display it.

I've also gotten reports that after a recent iOS update the tree started working, maybe you can check if there are any outstanding updates? And please post the iOS/Safari version before and after the update (if there is an update).

Apart from the tree the layout should never be broken, I'll fix that.

**Comment by Dav1dde** [comment]
Layout is fixed now

**Comment by Dav1dde** [comment]
Apparantely iOS 16.4.1 is a working version, can you see if you have that version or higher?

**Comment by Dav1dde** [comment]
I had a friend confirm that 16.4 is working, I cant really fix it for older versions without a mac/iOS device, so this is all I can do for now.
