### ISSUE TITLE
Foil items are not visible

### ISSUE THREAD

**Issue by jtuu** [Dav1dde/pasteofexile#14]
Random example: https://pobb.in/lXt2RdaK4jmG
The character has a foil Farrul's Fur equipped, but no body armour is displayed on pobb.in.

I suspect it has something to do with this piece of code. It should probably accept the "Relic" rarity:
https://github.com/Dav1dde/pasteofexile/blob/3ae93315eec65a13df21c8da12a8c77c3cb06200/pob/src/items.rs#L73-L79

**Comment by Dav1dde** [comment]
Thanks, you're correct Relic's arent currently correctly handled, when I initially implemented this, the Relic handling in PoB was broken and PoB stored them as uniques. I'll fix that!

**Comment by Dav1dde** [comment]
It's live now, should be able to see your glorious chest now ;)
