### ISSUE TITLE
Item images not displayed due to POB name mismatch

### ISSUE THREAD

**Issue by jtuu** [Dav1dde/pasteofexile#15]
Example: https://pobb.in/s1R4zx8Xp2mH
The weapon image is not displayed.

This seems to be caused by POB using slightly incorrect names for some items. The correct name of the weapon is "Mjölner", but POB uses the name "Mjolner" (ö -> o), which causes pobb.in to not be able to find the correct image file. There are more items that have this discrepancy in their name, for example "Maelström Staff".

**Comment by Dav1dde** [comment]
Mjölner (also Maelström of Chaos)  is displayed now, sorry for the delay, forgot about this issue.
