### ISSUE TITLE
Feature request: Custom modifiers

### ISSUE THREAD

**Issue by lvlvllvlvllvlvl** [Dav1dde/pasteofexile#22]
Would it be possible to show when there are custom modifiers on a build?

At minimum a line of text that says 'Custom modifiers' when the custom modifiers box on the configuration tab is not empty. If possible also the ability to expand it to see what the custom modifier text is. Ideal would be to highlight the text blue and red same as pob does.

**Comment by Dav1dde** [comment]
Highlighting the text wether it is a parsable mod or not won't be possible but the rest yes!

**Comment by Dav1dde** [comment]
First implementation never works as expected, people actually format that custom mods section, looks pretty nice if it is:

<img width="1028" alt="image" src="https://github.com/Dav1dde/pasteofexile/assets/255721/e217c317-d2b7-44ae-af18-8a756fc6f3f9">
