### ISSUE TITLE
Feature request: Show support gems in The Squire

### ISSUE THREAD

**Issue by Listerw** [Dav1dde/pasteofexile#23]
In builds that use the unique shield The Squire, the gems aren't shown even though they are still applied to the active skills in the main hand weapon. E.g. https://pobb.in/LWMgGFgeY1OA

They aren't shown due to not being directly linked to an active skill, but it'd be nice to see which gems are used in this case.

**Comment by Dav1dde** [comment]
Thanks, need to look into this, looks like there needs to be a special case for Squire.
