### ISSUE TITLE
Skill tree doesn't show up any more

### ISSUE THREAD

**Issue by Pangaea666** [Dav1dde/pasteofexile#25]
Am unsure when this started happening, but it worked before and now the skill tree no longer shows up. I'm on Firefox on PC/Linux. It works on mobile, where I also use Firefox. Have tried to disable extensions like Privacy Badger and uBlock Origin, but the tree still doesn't show up, so I'm not sure what is the cause of this. The keynodes and masteries show up in the right panel, but not the skill tree selection.

As an aside, the level listed is and skill points count is wrong, maybe due to the 2nd ascendancy tree we have now? The screenshot is with a level 92 character, yet it shows up as 99 in Pobb.in.

https://pobb.in/E_baMWebo_JQ
![Pobbin missing skill tree](https://github.com/Dav1dde/pasteofexile/assets/2002335/388058ba-1406-4380-b3c8-7fb4f8d3acf7)

**Comment by Dav1dde** [comment]
Can you try clearing your browser cache, I assume you have an old version of pobbin cached locally but an updated version of the tree.

If that does not help, please open the dev tools (F12) and check bottom right/console for any errors.

> As an aside, the level listed is and skill points count is wrong, maybe due to the 2nd ascendancy tree we have now? The screenshot is with a level 92 character, yet it shows up as 99 in Pobb.in.

Good catch, this is likely what is happening!

**Comment by Pangaea666** [comment]
> Can you try clearing your browser cache, I assume you have an old version of pobbin cached locally but an updated version of the tree.

Tried to clear it a few times, both via the 'keylock' for the site itself, and then globally via settings. Restarted Firefox too, but the skill tree still doesn't show up. It's odd, because I haven't changed anything, and it used to work before, and does work on my phone. Tried to disable all extensions, but that didn't do the trick either.

Am not familiar with that part of the dev tools, so let me know if I'm looking at the wrong parts. This is what shows up:

![Screenshot from 2024-01-16 18-10-32](https://github.com/Dav1dde/pasteofexile/assets/2002335/2b740afe-8df7-42cc-a3b6-b42267ef794b)

**Comment by Pangaea666** [comment]
Thanks for the instruction. The log is attached. A lot if fetched, but some assets appear to be blocked.

This happens on every build btw, not just the one from the first post. Any time I open up a build from reddit, discord servers or PoB, they never show up with the skill tree visible. 

Tried turning off all extensions again and reload the page. Skill tree doesn't show up then either, but fewer assets are blocked. But 3.23.svg is still blocked according to the log.

![Screenshot from 2024-01-19 08-53-22](https://github.com/Dav1dde/pasteofexile/assets/2002335/0402e7e2-3379-4115-9694-1c012e18ba37)

**Comment by Dav1dde** [comment]
Do you have a plugin called [CanvasBlocker](https://github.com/kkapsner/CanvasBlocker/tree/master) installed? If not can you click on `iframeProtection.js` in the network log (Initiator column) and screenshot where it takes you?

**Comment by Pangaea666** [comment]
Sorry for late feedback again. Wasn't busy playing the game. Promise! :D 

I do indeed have CanvasBlocker installed. However, even when I disabled all extensions, including CanvasBlocker, the skill tree still failed to show up. But since you mention that one specifically, maybe it is at fault for blocking the lines shown in the screenshot. With everything off, it was "only" the 3.23.svg that was blocked.

**Comment by Dav1dde** [comment]
I assume it's some privacy extension or firefox setting blocking access to the tree object/iframe. 

Can you run `document.getElementsByTagName('object')[0].contentWindow.tree_load` in the dev tools console and see what get's returned? It should look like this: 
![image](https://github.com/Dav1dde/pasteofexile/assets/255721/c43133ed-b9f6-40af-86e7-45d285f087a4)

The errors in the network tab are actually fine, this is just some weird interaction with pre loading where the same resource gets requested multiple times and the first requests are aborted in favor of the latest.

Also feel free to reach out to me `dav1d` on the official poe discord in the `#tooldev-general` channel.

**Comment by Pangaea666** [comment]
Hopefully I did this right, by copying what you wrote at the bottom of the Console in Dev Tools. Tested it with CanvasBlocker both enabled and disabled, but it yields the same message.

![canvasblockerOFF](https://github.com/Dav1dde/pasteofexile/assets/2002335/088afd07-b4c1-4a8a-95d4-1c9eb9fed6dc)

What I find a little odd is that I've used this set of extensions all the time, and previously the skill tree used fine. But ofc it's possible there has been an update to one of them, or even CanvasBlocker, or Firefox itself, that means the skill tree no longer shows up. Unless something has changed on pobb.in's side ofc.

**Comment by Dav1dde** [comment]
Something is blocking access to the `contentWindow` (basically the tree SVG). 

It doesnt seem to be Canvas Blocker, since even with it enabled on my Firefox it works.  Maybe some privacy setting changed in `about:config` or a (misconfigured) extension.

Not sure how to further debug this, you can try in incognito (that usually disables extensions) or with a fresh install/profile.

**Comment by Dav1dde** [comment]
The levels are now correct if all ascendancy passives are allocated, fixing it properly does require game data which I currently don't have available, will fix that eventually.

Regarding your issues feel free to reach out on discord.
