### ISSUE TITLE
Access blocked by cloudflare for exile-tools Gemplanner

### ISSUE THREAD

**Issue by dermow** [Dav1dde/pasteofexile#28]
Hey there!

Developing a tool called exile-tools Gemplanner for Path of eile. A tool that lets you paste your PoB-Date (or code) and tells you where you can get your Gems and so on. 

To make pasting more easy, there is a lookup function for different paste platforms - like pobb.in. 

I noticed a few days ago, that the lookup is not working anymore  because it is blocked by CloudFlare before it.

I am jusing Python / Requests to get the data:

```python
def get_from_pobb(self, code):
    url = f"https://pobb.in/pob/{code}"
    resp = requests.get(url)
    return resp.text
```

Is there any way I can get it working again? 

Thanks and kind regards

mow

**Comment by Dav1dde** [comment]
Hey, sure. Can you add a some kind of identifiable user agent, e.g. the format described here: https://github.com/Dav1dde/pasteofexile?tab=readme-ov-file#public-api

And then I need the IP to check the logs/exempt it from the firewall.

**Comment by Dav1dde** [comment]
I just saw you're using `url = f"https://pobb.in/pob/{code}"` please use the non pob API with the `/raw` suffix, e.g. `https://pobb.in/<code>/raw` or `https://pobb.in/u/<user>/<code>/raw` basically just `<url>/raw`.

**Comment by dermow** [comment]
Thanks for your fast reply! 
I implemented the new url and added the user agent:
```python
def get_from_pobb(self, code):
  url = f"https://pobb.in/{code}/raw"
  headers = {'User-Agent': 'exile-tools-gemplanner/1.0 (Contact: dermow@posteo.de)'}
  resp = requests.get(url, headers=headers)
  return resp.text
```

Tool is hosted on a server at netcup.de. 
Source IP: 45.9.62.141

Thanks!

**Comment by dermow** [comment]
Ah - noticed that I did not post the tool itself, if you are interested in:
https://exile-tools.com/gemplanner

**Comment by Dav1dde** [comment]
Sorry didn't see your reply for bed, should be all good now!

**Comment by dermow** [comment]
Integration is working again. Thanks a lot!
