### ISSUE TITLE
Feature request: case insensitive links

### ISSUE THREAD

**Issue by lvlvllvlvllvlvl** [Dav1dde/pasteofexile#29]
l've noticed a few people pasting build links that get converted to lowercase somehow, which then leads to a 404 error ([recent example](https://www.reddit.com/r/pathofexile/comments/1ar3z7d/comment/kqk5q23/?utm_source=reddit&utm_medium=web2x&context=3)). Not a big deal, as the user can just edit the link, but lowercase or case-insensitive links may be more user-friendly.

**Comment by Dav1dde** [comment]
Thanks for sharing the feedback.

I can't currently "auto correct" ids. While all new ids could only be lowercase, it wouldn't help with old ones.

I might change te id scheme in the future  but I feel like the current one has worked pretty well overall and made storage for me very easy.
