### ISSUE TITLE
Wrong Skill name used

### ISSUE THREAD

**Issue by ryuukk** [Dav1dde/pasteofexile#31]
https://pobb.in/PNOG151Zo98V

**Actual**:

``Level 96 Crit Siege Ballista of Splintering Assassin
3.24``

**Expected**:

``Level 96 Crit Galvanic Arrow of Energy Assassin
3.24``

![image](https://github.com/Dav1dde/pasteofexile/assets/44361234/c07b41ac-c8be-4941-8f55-fc55d44581a6)

**Comment by Dav1dde** [comment]
Looks like I am not checking for `enabled`:

```xml
<Gem enableGlobal2="true" level="20" gemId="Metadata/Items/Gems/SkillGemSiegeBallista" variantId="SiegeBallistaAltX" skillId="SiegeBallistaAltX" quality="20" qualityId="Default" enableGlobal1="true" enabled="false" count="4" nameSpec="Siege Ballista of Splintering"/>
```
