### ISSUE TITLE
Suggestion: Disable Guard skills by default

### ISSUE THREAD

**Issue by CountCocofang** [Dav1dde/pasteofexile#35]
Almost all builds inflate their EHP numbers with a Guard Skill that is either manually cast or linked to Automation. But in the majority of cases, especially for Steelskin, the uptime isn't even 50%.

So the usual problem is that you see some build with very high EHP on paper but then you open PoB to disable the Guard Skill and it instantly loses like 20-80% of its EHP pool. Which is what that build is actually running around with most of the time.

Meanwhile, the rare build that doesn't automate a Guard Skill is much more consistently and reliably tanky but might be beaten by a few thousand EHP by a build that only boasts that for one or two seconds at a time.

This is the same problem the now - thankfully - removed Berserk had. Where PoBs showed huge EHP and DPS numbers, yet disabling that one checkbox made it all deflate like a balloon.

So please disable Guard Skills by default. That way EHP values are more representative of the real in-game experience and not inflated by a buff that doesn't have permanent uptime.

**Comment by Dav1dde** [comment]
pobb.in is only displaying information not calculating it, so unfortunately I can't do anything about this on pobb.in, but you can open a feature request for [PoB](https://github.com/PathOfBuildingCommunity/PathOfBuilding/), if there isn't one already.
