### ISSUE TITLE
Interest in Business Acquisition / Partnership Discussion

### ISSUE THREAD

**Issue by MarinusElgaard** [Dav1dde/pasteofexile#37]
Hi @Dav1dde,

I'm reaching out regarding a potential business opportunity. I'm interested in discussing the possibility of acquiring or partnering with pasteofexile. I'd appreciate the opportunity to have a confidential discussion about this where you can hear more about our project, vision and ambitions.

Please let me know the best way to connect for a private conversation - whether through email, a call, or another channel you prefer.

Looking forward to hearing from you.
Best regards
Marinus Elgaard
CTO @ Chosen

**Comment by Dav1dde** [comment]
You can reach me via email `business@pobb.in` or discord `dav1d`.

**Comment by MarinusElgaard** [comment]
@Dav1dde Thanks for getting back to me this Quickly! 
I will reach out asap.
