### ISSUE TITLE
Bug: Switching gem sets does not switch the gem list

### ISSUE THREAD

**Issue by chasebrewsky** [Dav1dde/pasteofexile#8]
Example PoB: https://pobb.in/MqBwqqTLVBhW

This PoB has different sets of skill gems for leveling, but when a different gem set is selected in the dropdown for the gem selection it doesn't switch to that gem set; it only stays on the endgame set.

I tried this out in both Chrome + Firefox on computer and Chrome + Firefox + Safari on and iPad.

**Comment by Dav1dde** [comment]
Fixed with the next update on April 1st!
