### ISSUE TITLE
Bug: Tree preview does not work on tablets

### ISSUE THREAD

**Issue by chasebrewsky** [Dav1dde/pasteofexile#9]
Example PoB: https://pobb.in/MqBwqqTLVBhW

I tried viewing the passive tree for this PoB on an iPad mini, but the nodes were not highlighted. It just showed a greyed out tree. I tested this out on Chrome + Firefox + Safari on the iPad mini. It cannot be replicated by using the responsive testing features of chrome or firefox dev tools, only through a tablet. It does not occur on mobile.

**Comment by chasebrewsky** [comment]
This may be an issue related to iOS since my mobile phone is an android.

**Comment by Dav1dde** [comment]
What Safari version do you have on the ipad? Can you check if it works on a mac book? 

On iOS all browsers use the same engine iirc so it's not surprising all browser don't work. I assume it simply does not support the required SVG 2 features (styling nodes with CSS).

**Comment by chasebrewsky** [comment]
It's running iPadOS 16.3.1, so safari 16. I'm checking this on a macbook right now and it works here.

Now that I'm looking closely at it, it does look like the lines for the path exist on the iPad but are just not colored correctly. I see that `stroke="currentColor"` is set on the parent `g` element and each line or path that should be highlighted that color has their CSS `color=#colornum`. I'm curious if in iOS it doesn't cascade the parents `stroke` property and expects an explicit attribute set on each element.

**Comment by chasebrewsky** [comment]
Nope, just read that the g element is supposed to cascade attributes to children.

**Comment by chasebrewsky** [comment]
You're probably right that it's just iOS being behind the times on the spec. That's a shame.

**Comment by Dav1dde** [comment]
I would like to support it, but they make it incredibly hard (basically impossible) to test without getting a mac book *and* a mobile device/ipad :(
